/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely"

export type Generated<T> =
    T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>

export type Json = JsonValue

export type JsonArray = JsonValue[]

export type JsonObject = {
    [x: string]: JsonValue | undefined
}

export type JsonPrimitive = boolean | number | string | null

export type JsonValue = JsonArray | JsonObject | JsonPrimitive

export type QueueJobState = "active" | "cancelled" | "completed" | "created" | "failed" | "retry"

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export type UserRole = "admin" | "customer" | "manager"

export interface AuthUsers {
    created_at: Generated<Timestamp>
    email: string
    email_verified: Generated<boolean>
    id: Generated<number>
    is_banned: Generated<boolean>
    password: string
    role: Generated<UserRole>
    updated_at: Generated<Timestamp>
}

export interface Cache {
    created_at: Generated<Timestamp>
    expires_at: Timestamp | null
    key: string
    value: Json
}

export interface QueueBam {
    command: string
    completed_on: Timestamp | null
    created_on: Generated<Timestamp>
    error: string | null
    id: Generated<string>
    name: string
    queue: string | null
    started_on: Timestamp | null
    status: Generated<string>
    table_name: string
    version: number
}

export interface QueueJob {
    completed_on: Timestamp | null
    created_on: Generated<Timestamp>
    data: Json | null
    dead_letter: string | null
    deletion_seconds: Generated<number>
    expire_seconds: Generated<number>
    group_id: string | null
    group_tier: string | null
    heartbeat_on: Timestamp | null
    heartbeat_seconds: number | null
    id: Generated<string>
    keep_until: Generated<Timestamp>
    name: string
    output: Json | null
    policy: string | null
    priority: Generated<number>
    retry_backoff: Generated<boolean>
    retry_count: Generated<number>
    retry_delay: Generated<number>
    retry_delay_max: number | null
    retry_limit: Generated<number>
    singleton_key: string | null
    singleton_on: Timestamp | null
    start_after: Generated<Timestamp>
    started_on: Timestamp | null
    state: Generated<QueueJobState>
}

export interface QueueQueue {
    active_count: Generated<number>
    created_on: Generated<Timestamp>
    dead_letter: string | null
    deferred_count: Generated<number>
    deletion_seconds: number
    expire_seconds: number
    heartbeat_seconds: number | null
    maintain_on: Timestamp | null
    monitor_on: Timestamp | null
    name: string
    partition: boolean
    policy: string
    queued_count: Generated<number>
    retention_seconds: number
    retry_backoff: boolean
    retry_delay: number
    retry_delay_max: number | null
    retry_limit: number
    singletons_active: string[] | null
    table_name: string
    total_count: Generated<number>
    updated_on: Generated<Timestamp>
    warning_queued: Generated<number>
}

export interface QueueSchedule {
    created_on: Generated<Timestamp>
    cron: string
    data: Json | null
    key: Generated<string>
    name: string
    options: Json | null
    timezone: string | null
    updated_on: Generated<Timestamp>
}

export interface QueueSubscription {
    created_on: Generated<Timestamp>
    event: string
    name: string
    updated_on: Generated<Timestamp>
}

export interface QueueVersion {
    bam_on: Timestamp | null
    cron_on: Timestamp | null
    version: number
}

export interface QueueWarning {
    created_on: Generated<Timestamp>
    data: Json | null
    id: Generated<string>
    message: string
    type: string
}

export interface SchemaMigrations {
    version: string
}

export interface DB {
    auth_users: AuthUsers
    cache: Cache
    "queue.bam": QueueBam
    "queue.job": QueueJob
    "queue.queue": QueueQueue
    "queue.schedule": QueueSchedule
    "queue.subscription": QueueSubscription
    "queue.version": QueueVersion
    "queue.warning": QueueWarning
    schema_migrations: SchemaMigrations
}
