/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely"

export type Generated<T> =
    T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>

export type Json = JsonValue

export type JsonArray = JsonValue[]

export type JsonObject = {
    [x: string]: JsonValue | undefined
}

export type JsonPrimitive = boolean | number | string | null

export type JsonValue = JsonArray | JsonObject | JsonPrimitive

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export type UserRole = "admin" | "customer" | "manager"

export interface AuthUsers {
    created_at: Generated<Timestamp>
    email: string
    email_verified: Generated<boolean>
    id: Generated<number>
    is_banned: Generated<boolean>
    password: string
    role: Generated<UserRole>
    updated_at: Generated<Timestamp>
}

export interface Cache {
    created_at: Generated<Timestamp>
    expires_at: Timestamp | null
    key: string
    value: Json
}

export interface DimPlant {
    created_at: Generated<Timestamp>
    plant_id: Generated<number>
    plant_id_parent: number | null
    plant_name: string
    plant_type_id: number
    updated_at: Generated<Timestamp>
}

export interface DimPlantType {
    created_at: Generated<Timestamp>
    plant_type_id: Generated<number>
    plant_type_name: string
    updated_at: Generated<Timestamp>
}

export interface SchemaMigrations {
    version: string
}

export interface DB {
    auth_users: AuthUsers
    cache: Cache
    dim_plant: DimPlant
    dim_plant_type: DimPlantType
    schema_migrations: SchemaMigrations
}
